# Generated by Django 5.2 on 2025-05-06 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('ni', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura (°C)'), ('luminosidade', 'Luminosidade (lux)'), ('umidade', 'Umidade (%)'), ('contador', 'Contador (num)')], max_length=12)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('valor', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7)),
                ('timestamp', models.CharField(max_length=20)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='api.ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField()),
                ('timestamp', models.CharField(max_length=20)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='api.ambiente')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='api.sensor')),
            ],
        ),
    ]
