# Generated by Django 5.1.1 on 2025-05-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_historico_options_remove_historico_ambiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ambiente'),
        ),
    ]
